"""add quote_lines.source_line_id for revision provenance

Revision ID: 26bdcb293597
Revises: 91563b112f87
Create Date: 2026-09-05 22:16:00.443295
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '26bdcb293597'
down_revision: Union[str, None] = '91563b112f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_lines', sa.Column('source_line_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_quote_lines_source_line_id'), 'quote_lines', ['source_line_id'], unique=False)
    op.create_foreign_key(op.f('fk_quote_lines_source_line_id_quote_lines'), 'quote_lines', 'quote_lines', ['source_line_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_quote_lines_source_line_id_quote_lines'), 'quote_lines', type_='foreignkey')
    op.drop_index(op.f('ix_quote_lines_source_line_id'), table_name='quote_lines')
    op.drop_column('quote_lines', 'source_line_id')
    # ### end Alembic commands ###
