"""quote line order discount share and effective discount pct

Revision ID: 7b431beeb960
Revises: 8a95724d5377
Create Date: 2026-09-06 03:02:03.598408
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b431beeb960'
down_revision: Union[str, None] = '8a95724d5377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_lines', sa.Column('order_discount_amount', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('quote_lines', sa.Column('effective_discount_pct', sa.Numeric(precision=9, scale=4), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_lines', 'effective_discount_pct')
    op.drop_column('quote_lines', 'order_discount_amount')
    # ### end Alembic commands ###
