"""settings, sales teams, credit notes, order discount, delivery promise, attention actions

Revision ID: 8a95724d5377
Revises: 26bdcb293597
Create Date: 2026-09-06 02:58:26.861477
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8a95724d5377'
down_revision: Union[str, None] = '26bdcb293597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_settings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('finance_escalation_threshold', sa.Numeric(precision=9, scale=4), server_default=sa.text('60.0'), nullable=False),
    sa.Column('risk_discount_overage_weight', sa.Numeric(precision=9, scale=4), server_default=sa.text('3.0'), nullable=False),
    sa.Column('risk_breadth_weight', sa.Numeric(precision=9, scale=4), server_default=sa.text('5.0'), nullable=False),
    sa.Column('risk_margin_weight', sa.Numeric(precision=9, scale=4), server_default=sa.text('5.0'), nullable=False),
    sa.Column('risk_depth_weight', sa.Numeric(precision=9, scale=4), server_default=sa.text('0.4'), nullable=False),
    sa.Column('stalled_deal_days', sa.Integer(), server_default=sa.text('14'), nullable=False),
    sa.Column('discount_anomaly_sigma', sa.Numeric(precision=9, scale=4), server_default=sa.text('2.0'), nullable=False),
    sa.Column('discount_anomaly_min_samples', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('approval_sla_hours', sa.Integer(), server_default=sa.text('24'), nullable=False),
    sa.Column('recommendation_min_margin_pct', sa.Numeric(precision=9, scale=4), server_default=sa.text('0.0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint('approval_sla_hours >= 1', name=op.f('ck_organization_settings_approval_sla_positive')),
    sa.CheckConstraint('discount_anomaly_min_samples >= 2', name=op.f('ck_organization_settings_anomaly_min_samples_meaningful')),
    sa.CheckConstraint('discount_anomaly_sigma > 0', name=op.f('ck_organization_settings_anomaly_sigma_positive')),
    sa.CheckConstraint('stalled_deal_days >= 1', name=op.f('ck_organization_settings_stalled_deal_days_positive')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_settings_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_settings')),
    sa.UniqueConstraint('organization_id', name='uq_organization_settings_organization_id')
    )
    op.create_index(op.f('ix_organization_settings_created_at'), 'organization_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_settings_organization_id'), 'organization_settings', ['organization_id'], unique=False)
    op.create_table('sales_teams',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager_user_id', sa.UUID(), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], name=op.f('fk_sales_teams_manager_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sales_teams_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_teams')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_sales_teams_organization_id_code')
    )
    op.create_index(op.f('ix_sales_teams_created_at'), 'sales_teams', ['created_at'], unique=False)
    op.create_index(op.f('ix_sales_teams_manager_user_id'), 'sales_teams', ['manager_user_id'], unique=False)
    op.create_index(op.f('ix_sales_teams_organization_id'), 'sales_teams', ['organization_id'], unique=False)
    op.create_index('ix_sales_teams_organization_id_is_active', 'sales_teams', ['organization_id', 'is_active'], unique=False)
    op.create_table('sales_team_members',
    sa.Column('sales_team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sales_team_members_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_team_id'], ['sales_teams.id'], name=op.f('fk_sales_team_members_sales_team_id_sales_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sales_team_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_team_members')),
    sa.UniqueConstraint('sales_team_id', 'user_id', name='uq_sales_team_members_sales_team_id_user_id')
    )
    op.create_index(op.f('ix_sales_team_members_created_at'), 'sales_team_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_sales_team_members_organization_id'), 'sales_team_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sales_team_members_sales_team_id'), 'sales_team_members', ['sales_team_id'], unique=False)
    op.create_index('ix_sales_team_members_user_id', 'sales_team_members', ['user_id'], unique=False)
    op.create_table('dismissed_recommendations',
    sa.Column('quote_version_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('dismissed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['dismissed_by_user_id'], ['users.id'], name=op.f('fk_dismissed_recommendations_dismissed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_dismissed_recommendations_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_dismissed_recommendations_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.id'], name=op.f('fk_dismissed_recommendations_quote_version_id_quote_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dismissed_recommendations')),
    sa.UniqueConstraint('quote_version_id', 'product_id', name='uq_dismissed_recommendations_quote_version_id_product_id')
    )
    op.create_index(op.f('ix_dismissed_recommendations_created_at'), 'dismissed_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_dismissed_recommendations_organization_id'), 'dismissed_recommendations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dismissed_recommendations_quote_version_id'), 'dismissed_recommendations', ['quote_version_id'], unique=False)
    op.create_table('credit_notes',
    sa.Column('credit_note_number', sa.String(length=64), nullable=False),
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('billing_schedule_id', sa.UUID(), nullable=True),
    sa.Column('customer_organization_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'APPLIED', 'VOID', name='ck_creditnotestatus', native_enum=False, length=48), nullable=False),
    sa.Column('reason', sa.Enum('SUBSCRIPTION_CANCELLED', 'SUBSCRIPTION_DOWNGRADED', 'ORDER_CANCELLED', 'BILLING_CORRECTION', 'GOODWILL', name='ck_creditnotereason', native_enum=False, length=48), nullable=False),
    sa.Column('reason_note', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_refunded', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('issued_by_user_id', sa.UUID(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint('amount_refunded >= 0 AND amount_refunded <= total_amount', name=op.f('ck_credit_notes_amount_refunded_within_total')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_credit_notes_subtotal_non_negative')),
    sa.CheckConstraint('tax_amount >= 0', name=op.f('ck_credit_notes_tax_amount_non_negative')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_credit_notes_total_amount_non_negative')),
    sa.ForeignKeyConstraint(['billing_schedule_id'], ['billing_schedules.id'], name=op.f('fk_credit_notes_billing_schedule_id_billing_schedules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_organization_id'], ['organizations.id'], name=op.f('fk_credit_notes_customer_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_credit_notes_invoice_id_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], name=op.f('fk_credit_notes_issued_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_credit_notes_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name=op.f('fk_credit_notes_sales_order_id_sales_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_notes')),
    sa.UniqueConstraint('organization_id', 'credit_note_number', name='uq_credit_notes_organization_id_credit_note_number')
    )
    op.create_index(op.f('ix_credit_notes_billing_schedule_id'), 'credit_notes', ['billing_schedule_id'], unique=False)
    op.create_index(op.f('ix_credit_notes_created_at'), 'credit_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_notes_invoice_id'), 'credit_notes', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_credit_notes_organization_id'), 'credit_notes', ['organization_id'], unique=False)
    op.create_index('ix_credit_notes_organization_id_status', 'credit_notes', ['organization_id', 'status'], unique=False)
    op.create_index('ix_credit_notes_sales_order_id', 'credit_notes', ['sales_order_id'], unique=False)
    op.add_column('attention_items', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attention_items', sa.Column('acknowledged_by_user_id', sa.UUID(), nullable=True))
    op.add_column('attention_items', sa.Column('nudge_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('attention_items', sa.Column('last_nudged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attention_items', sa.Column('last_nudged_by_user_id', sa.UUID(), nullable=True))
    op.add_column('attention_items', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attention_items', sa.Column('escalated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('attention_items', sa.Column('escalation_note', sa.Text(), nullable=True))
    op.create_foreign_key(op.f('fk_attention_items_last_nudged_by_user_id_users'), 'attention_items', 'users', ['last_nudged_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_attention_items_acknowledged_by_user_id_users'), 'attention_items', 'users', ['acknowledged_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_attention_items_escalated_by_user_id_users'), 'attention_items', 'users', ['escalated_by_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('products', sa.Column('is_promoted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('quote_versions', sa.Column('order_discount_pct', sa.Numeric(precision=9, scale=4), server_default=sa.text('0'), nullable=False))
    op.add_column('quote_versions', sa.Column('order_discount_amount', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('sales_order_lines', sa.Column('promised_delivery_date', sa.Date(), nullable=True))
    op.add_column('sales_orders', sa.Column('promised_delivery_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_orders', 'promised_delivery_date')
    op.drop_column('sales_order_lines', 'promised_delivery_date')
    op.drop_column('quote_versions', 'order_discount_amount')
    op.drop_column('quote_versions', 'order_discount_pct')
    op.drop_column('products', 'is_promoted')
    op.drop_constraint(op.f('fk_attention_items_escalated_by_user_id_users'), 'attention_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_attention_items_acknowledged_by_user_id_users'), 'attention_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_attention_items_last_nudged_by_user_id_users'), 'attention_items', type_='foreignkey')
    op.drop_column('attention_items', 'escalation_note')
    op.drop_column('attention_items', 'escalated_by_user_id')
    op.drop_column('attention_items', 'escalated_at')
    op.drop_column('attention_items', 'last_nudged_by_user_id')
    op.drop_column('attention_items', 'last_nudged_at')
    op.drop_column('attention_items', 'nudge_count')
    op.drop_column('attention_items', 'acknowledged_by_user_id')
    op.drop_column('attention_items', 'acknowledged_at')
    op.drop_index('ix_credit_notes_sales_order_id', table_name='credit_notes')
    op.drop_index('ix_credit_notes_organization_id_status', table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_organization_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_invoice_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_created_at'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_billing_schedule_id'), table_name='credit_notes')
    op.drop_table('credit_notes')
    op.drop_index(op.f('ix_dismissed_recommendations_quote_version_id'), table_name='dismissed_recommendations')
    op.drop_index(op.f('ix_dismissed_recommendations_organization_id'), table_name='dismissed_recommendations')
    op.drop_index(op.f('ix_dismissed_recommendations_created_at'), table_name='dismissed_recommendations')
    op.drop_table('dismissed_recommendations')
    op.drop_index('ix_sales_team_members_user_id', table_name='sales_team_members')
    op.drop_index(op.f('ix_sales_team_members_sales_team_id'), table_name='sales_team_members')
    op.drop_index(op.f('ix_sales_team_members_organization_id'), table_name='sales_team_members')
    op.drop_index(op.f('ix_sales_team_members_created_at'), table_name='sales_team_members')
    op.drop_table('sales_team_members')
    op.drop_index('ix_sales_teams_organization_id_is_active', table_name='sales_teams')
    op.drop_index(op.f('ix_sales_teams_organization_id'), table_name='sales_teams')
    op.drop_index(op.f('ix_sales_teams_manager_user_id'), table_name='sales_teams')
    op.drop_index(op.f('ix_sales_teams_created_at'), table_name='sales_teams')
    op.drop_table('sales_teams')
    op.drop_index(op.f('ix_organization_settings_organization_id'), table_name='organization_settings')
    op.drop_index(op.f('ix_organization_settings_created_at'), table_name='organization_settings')
    op.drop_table('organization_settings')
    # ### end Alembic commands ###
